### ISSUE TITLE
The size of an image is determined by the page width not by the size of the image on the page

### ISSUE THREAD

**Issue by shyim** [shopwareBoostDay/platform#409] opened 2021-12-15 14:03 UTC
**Description**  
When an image is shown in the storefront and the size of the browser window is large, the original image is loaded. Even if the image is only displayed with small dimensions. The image should, however, be picked based on the image size not the window width.

This obviously leads to considerable performance issues in the storefront.

With a large image view:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/31041526/92778165-34d6d480-f3a1-11ea-9298-4724ff7fe946.png">

The displayed image:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/31041526/92778223-3ef8d300-f3a1-11ea-8828-2b89c89b32d6.png">

With a small image view:
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/31041526/92778287-4e781c00-f3a1-11ea-817e-1d314ee3ebce.png">

The displayed image:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/31041526/92778333-58018400-f3a1-11ea-8e75-7837ef0a926e.png">

**Possible Solution**  
I am not fully certain, how the CSS should be here. It seems that with the correct `sizes` attributes a browser can do a better job of picking which size of image to load.
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
https://css-tricks.com/responsive-images-css/

**Comment by johannesdachsel** [comment] 2021-12-16 09:22
I'm not able to reproduce this issue but maybe I am missing something. These are the steps I've taken so far:

1. Upload an image to an existing product
2. Set image as cover and save product
3. Visit category page that has the changed product
![Screenshot 2021-12-16 at 10 20 39](https://user-images.githubusercontent.com/11289603/146343819-9891f352-cd94-4b3b-aa83-74ae77a6f3e7.png)
![Screenshot 2021-12-16 at 10 20 55](https://user-images.githubusercontent.com/11289603/146343825-183dc16b-2a39-427b-9736-dd075cf1ed19.png)

Is there anything I missed or I can do to reproduce the issue?

**Comment by rherwig** [comment] 2021-12-16 10:31
@johannesdachsel I followed your exact approach and achieved the same results. This makes me think that the initial bug occurred in an earlier version of Shopware 6.

The `sizes` query for the image in question is as follows:
`(min-width: 1200px) 280px, (min-width: 992px) 350px, (min-width: 768px) 390px, (min-width: 576px) 315px, (min-width: 0px) 500px, 100vw`

This means, that the largest possible thumbnail size for the image is (assuming thumbnail generation has not been altered) 800x800 px - which is used when the `min-width` of `576px` is not reached.

In order to achieve even better thumbnail sizes, I think one would have to generate the thumbnails according to bootstrap's breakpoints and approximate the most sensible sizes based on the grid layout. The responsiveness function of `picture` and `srcset` only takes the screen-width into account. If one wanted to account for the actually displayed size of the image, this could (imo) only be achieved using lazy loading - which is not greay for above the fold content.

In my opinion, this issue can be closed, since the original bug is no longer reproducible and the rendered image sizes are okay.

What do you think @johannesdachsel and @shyim?

**Comment by shyim** [comment] 2021-12-16 10:32
@tobiasberge Can you look here

**Comment by tobiasberge** [comment] 2021-12-16 12:16
@shyim It should be fixed with https://github.com/shopware/platform/commit/b54cb382a6fc68e788b32ed81d4926b26437f929

With this change the original images should never be used as soon as thumbnails are generated. The only exception is the image zoom on the detail page. I cannot reproduce it on current trunk, in the listing I get the 400x400 image on 3440px resolution for the product box image.

**Closed as completed** 2021-12-16 12:16 UTC
