### ISSUE TITLE
Not Possible to change Title of Media in Firefox

### ISSUE THREAD

**Issue by shyim** [shopwareBoostDay/platform#412] opened 2021-12-15 14:04 UTC
Beschreibung: It is not possible to change the title of Media in the SW6 Backend using a Firefox Browser. 

Umgebung: MacOS Mojave 10.14.6 (18G95). Firefox (v78.0.1 (64-Bit) on Mac)

Schritte zur Reproduktion: Login into backend. change media title. reload page and see that title was not persisted.

Erwartetes Ergebnis: new title is persisted

Tatsächliches Ergebnis: no/old title

**Comment by aragon999** [comment] 2021-12-16 10:45
I cannot reproduce this issue in Firefox 95 on Linux.

But I noticed some odd behavior where I am not sure how or if this should be fixed. If you do not press enter or the blue submit button after changing the title (same is true for the alt), the PATCH request is not sent which it might explain this issue, that it was assumed it should be saved anyway.

**Closed as completed** 2021-12-16 13:37 UTC
